### ISSUE TITLE
[Bug] Tapping once on the board doesn't draw.

### ISSUE THREAD

**Issue by harshhhdev** [harshhhdev/sketchmessage#1]
If you just tap one time on the canvas, nothing is drawn.

**Comment by SeanLuo-FSWD** [comment]
Hi there, 

Do you have the backend code published as well?

Thanks

**Comment by harshhhdev** [comment]
I do, yes :)

**Comment by SeanLuo-FSWD** [comment]
Sorry, but it seems to be missing the server.js file to start the app?

**Comment by harshhhdev** [comment]
Oh, really sorry about that. I've added it :+1:

**Comment by harshhhdev** [comment]
Closed #3
