### ISSUE TITLE
[Bug] Draws even after cursor is released

### ISSUE THREAD

**Issue by hardikchopra242** [harshhhdev/sketchmessage#2]
**Steps to Reproduce** 
1. Draw on the canvas using the left click.
2. Release the cursor outside the canvas
3. Then hover the cursor back on the canvas. 

**Expected Behaviour**
- Nothing should be drawn as the cursor is already released

**Current Behaviour**
- The cursor draws on hovering over the canvas.

**Comment by siddharthmagadum16** [comment]
Hey, can you assign it to me?

**Comment by siddharthmagadum16** [comment]
@harshhhdev  nice and simple project. I really liked it. By the way, can you tell me the reason why `sokect.emit('mose',c)`  duplicated once after this [line](https://github.com/harshhhdev/sketchmessage/blob/8f5fc90cd8f2acd46fa47ed0058e61c39bcf156a/public/scripts/main.js#L50)? If it is not for a purpose, shall I remove that duplication in my PR?

**Comment by harshhhdev** [comment]
> @harshhhdev nice and simple project. I really liked it. By the way, can you tell me the reason why `sokect.emit('mouse',c)` duplicated once after this [line](https://github.com/harshhhdev/sketchmessage/blob/8f5fc90cd8f2acd46fa47ed0058e61c39bcf156a/public/scripts/main.js#L50)? If it is not for a purpose, shall I remove that duplication in my PR?

Whoops, seems like an accident. You can go ahead & remove it

**Comment by harshhhdev** [comment]
Closed #3
